[package]
name = "freshfetch"
version = "0.1.0"
authors = ["K4rakara <jack@insertdomain.name>"]
edition = "2018"
build = "./src/build.rs"

[dependencies]
term_size = "0.3.2"
uname = "0.1.1"
cpuid = "0.1.1"
cmd_lib = "0.8.2"
mlua = "0.4.1"
chrono = "0.4.13"
users = "0.10.0"
regex = "1.3.9"

[dependencies.clap]
version = "2.33.2"
default-features = false
features = [ "vec_map" ]

[dependencies.clml_rs]
git = "https://github.com/K4rakara/clml-rs"
features = [ "advanced" ]

[build-dependencies.clml_rs]
git = "https://github.com/K4rakara/clml-rs"
